# Generated by Django 4.2.30 on 2026-10-08 23:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tiempo_preparacion_min', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('vehiculo', models.CharField(default='moto', max_length=30)),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('EN_REPARTO', 'En reparto'), ('INACTIVO', 'Inactivo')], default='DISPONIBLE', max_length=20)),
                ('capacidad_max', models.PositiveSmallIntegerField(default=3)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('latitud_centro', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitud_centro', models.DecimalField(decimal_places=6, max_digits=9)),
                ('tiempo_viaje_min', models.PositiveSmallIntegerField(help_text='Minutos estimados de viaje hasta esta zona')),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('ADMINISTRADOR', 'Administrador'), ('ENCARGADO', 'Encargado')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfiles',
                'ordering': ['rol'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion_entrega', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('token_seguimiento', models.CharField(editable=False, max_length=32, unique=True)),
                ('tiempo_estimado_min', models.PositiveSmallIntegerField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='daroth_app.cliente')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='daroth_app.repartidor')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='daroth_app.zona')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo'), ('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], max_length=20)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='daroth_app.pedido')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'HistorialEstado',
                'verbose_name_plural': 'HistorialEstados',
                'ordering': ['pedido'],
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=12)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='daroth_app.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='daroth_app.producto')),
            ],
            options={
                'verbose_name': 'DetallePedido',
                'verbose_name_plural': 'DetallePedidos',
                'ordering': ['pedido'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='zona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clientes', to='daroth_app.zona'),
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('mensaje', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='daroth_app.pedido')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['pedido'],
            },
        ),
        migrations.AddConstraint(
            model_name='detallepedido',
            constraint=models.UniqueConstraint(fields=('pedido', 'producto'), name='uq_detalle_pedido_producto'),
        ),
    ]
